spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/viboot?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Passw0rd

logging:
  level:
    indi.viyoung.viboot: debug
    file:
